SmartEdu/Controllers/_LayoutController.cs
using SmartEdu.Models.ORM.Context;
using SmartEdu.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartEdu.Controllers
{
    public class _LayoutController : Controller
    {
        private SiteContext db = new SiteContext();


        
        public ActionResult CallHeader()
        {
            LayoutModel mdl = new LayoutModel();
            List<ImageModel> ImageList = new List<ImageModel>();
            List<ContactModel> IletisimList = new List<ContactModel>();

            var ımageentities = db.İmages.Where(x => x.Type == 0).ToList();
            var contactentities = db.İletisims.Where(x => x.ID == 1).ToList();

            foreach (var item in ımageentities)
            {
                ImageModel ımgmodel = new ImageModel();
                ımgmodel.Type = item.Type;
                ımgmodel.Title = item.ResimBaslik;
                ımgmodel.Class = item.ImageClass;
                ımgmodel.ImagePath = item.ResimYolu;

                ImageList.Add(ımgmodel);
            }

            foreach (var contact in contactentities)
            {
                ContactModel ıletisimmodel = new ContactModel();

                ıletisimmodel.IletisimId = contact.ID;
                ıletisimmodel.Whatsapp = contact.Whatsapp;

                IletisimList.Add(ıletisimmodel);
            }

            mdl.VmIletisim = IletisimList;
            mdl.VmImage = ImageList;
            return PartialView("~/Views/Shared/_Header.cshtml", mdl);
        }

        
        public ActionResult CallFooter()
        {
            LayoutModel mdl = new LayoutModel();
            List<ContactModel> IletisimList = new List<ContactModel>();

            var contactentities = db.İletisims.Where(x => x.ID == 1).ToList();

            foreach (var contact in contactentities)
            {
                ContactModel ıletisimmodel = new ContactModel();

                ıletisimmodel.IletisimId = contact.ID;
                ıletisimmodel.Telefon = contact.Telefon;
                ıletisimmodel.Adres = contact.Adres;
                ıletisimmodel.Instagram = contact.İnstagram;
                ıletisimmodel.Twitter = contact.Twitter;
                ıletisimmodel.Facebook = contact.Facebook;
                ıletisimmodel.Youtube = contact.Youtube;
                ıletisimmodel.Whatsapp = contact.Whatsapp;

                IletisimList.Add(ıletisimmodel);
            }
            mdl.VmIletisim = IletisimList;

            return PartialView("~/Views/Shared/_Footer.cshtml", mdl);
        }
    }
}

SmartEdu/Views/Shared/_Footer.cshtml
@model SmartEdu.Models.ViewModels.LayoutModel


 @{
     var phone = Model.VmIletisim.FirstOrDefault(x => x.IletisimId == 1).Telefon;
     string telefon = phone.Replace("tel://+9", "");
  }
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-xs-12">
                <div class="widget clearfix ">
                    <div class="widget-title">
                        <h3>Bizi Takip Edin</h3>
                    </div>
                    <br />
                    <ul class="footer-links-soi ">
                        <li><a href="@Model.VmIletisim.FirstOrDefault(x=>x.IletisimId ==1).Facebook" target="_blank"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="@Model.VmIletisim.FirstOrDefault(x=>x.IletisimId ==1).Twitter" target="_blank"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="@Model.VmIletisim.FirstOrDefault(x=>x.IletisimId ==1).Instagram" target="_blank"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="@Model.VmIletisim.FirstOrDefault(x=>x.IletisimId ==1).Youtube" target="_blank"><i class="fa fa-youtube"></i></a></li>
                    </ul><!-- end links -->
                </div><!-- end clearfix -->
            </div><!-- end col -->
            <div class="col-lg-4 col-md-4 col-xs-12">
                <div class="widget clearfix">
                    <div class="widget-title">
                        <h3>Bağlantılar</h3>
                    </div>
                    <ul class="footer-links">
                        <li><a href="/">Anasayfa</a></li>
                        <li><a href="/Hakkimizda">Hakkımızda </a></li>
                        <li><a href="/İletisim">İletişim</a></li>
                    </ul><!-- end links -->
                </div><!-- end clearfix -->
            </div><!-- end col -->
            <div class="col-lg-4 col-md-4 col-xs-12">
                <div class="widget clearfix">
                    <div class="widget-title">
                        <h3>İletişim</h3>
                    </div>
                    <ul class="footer-links">
                        <li>@Html.Raw(Model.VmIletisim.FirstOrDefault(x=>x.IletisimId ==1).Adres)</li>        
                        
                        <li><a class="btn btn-primary" href="@Model.VmIletisim.FirstOrDefault(x=>x.IletisimId ==1).Telefon" title="telefon">İletisim: @telefon </a></li>
                    </ul><!-- end links -->
                </div><!-- end clearfix -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div>
</footer>

SmartEdu/Views/Shared/_Header.cshtml
@model SmartEdu.Models.ViewModels.LayoutModel

<header class="top-navbar">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <img src="@Model.VmImage.FirstOrDefault(x=>x.Title =="Logo").ImagePath" />
            </a>
            <div class="navbar-left mr-auto" style="padding-left:20px">
                <a href="@Model.VmIletisim.FirstOrDefault(x=>x.IletisimId == 1).Whatsapp" target="_blank"><img src="@Model.VmImage.FirstOrDefault(x=>x.Title =="Whatsapp").ImagePath" title="Whatsappla Ulaşın" class="float"></a>
            </div>
            <button class="navbar-toggler collapsed" aria-expanded="false" aria-controls="navbars-rs-food" aria-label="Toggle navigation" type="button" data-toggle="collapse" data-target="#navbars-host">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbars-host">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="/">Anasayfa</a></li>
                    <li class="nav-item "><a class="nav-link" href="/Hakkimizda">Hakkımızda</a></li>
                    <li class="nav-item"><a class="nav-link" href="/İletisim">İletişim</a></li>
                </ul>
            </div>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </div><!--Container-->
    </nav>
</header>

SmartEdu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Site Metas -->
    <title>01 | Adana Özel Ders</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    
    <!-- Site Icons -->
    <link rel="shortcut icon" href="@Url.Content("~/Content/Site/images/favicon.ico")" type="image/x-icon" />

    <link rel="apple-touch-icon" href="@Url.Content("~/Content/Site/images/apple-touch-icon.png")">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="@Url.Content("~/Content/Site/css/bootstrap.min.css")">
    <!-- Site CSS -->
    <link rel="stylesheet" href="@Url.Content("~/Content/Site/css/style.css")">
    <!-- ALL VERSION CSS -->
    <link rel="stylesheet" href="@Url.Content("~/Content/Site/css/versions.css")">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="@Url.Content("~/Content/Site/css/responsive.css")">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="@Url.Content("~/Content/Site/css/custom.css")">
    <!-- Modernizer for Portfolio -->
    <script src="@Url.Content("~/Content/Site/js/modernizer.js")"></script>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="host_version">
    <!-- LOADER -->
    <div id="preloader">
        <div class="loader-container">
            <div class="progress-br float shadow">
                <div class="progress__item"></div>
            </div>
        </div>
    </div>
    <!-- END LOADER -->
    
    <!-- Start header -->
        @{Html.RenderAction("CallHeader", "_Layout"); }
    <!-- End header -->
    
    
        @RenderBody()

    <!--Start Footer-->
   @{Html.RenderAction("CallFooter", "_Layout"); }
    <!-- end footer -->

   <!--Copyrights--> 
    <div class="copyrights">
        <div class="container">
            <div class="footer-distributed">
                <div class="footer-center">
                    <p class="footer-company-name">Tüm Hakları Saklıdır. &copy; 2019 <a href="http://umsayazilim.com/" target="_blank">UMSA YAZILIM</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- end copyrights -->
    
        <!-- Yukarı Çıkma Butonu -->
    <a href="#" id="scroll-to-top" class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>

    <!-- Tüm JavaScript Dosyaları -->
    @*<script src="@Url.Content("~/Scripts/jquery-3.0.0.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-3.0.0.js")"></script>*@
    <script src="@Url.Content("~/Content/Site/js/all.js")"></script>
   
    <!-- Tüm Eklentiler -->
    <script src="~/Content/Site/js/custom.js"></script>
    <script src="~/Content/Site/js/timeline.min.js"></script>
   
    
    <script>
            timeline(document.querySelectorAll('.timeline'), {
                forceVerticalMode: 700,
                mode: 'horizontal',
                verticalStartPosition: 'left',
                visibleItems: 4
            });
    </script> 

</body>
</html>

SmartEdu/Views/Shared/_LayoutAdmin.cshtml
<!doctype html>

<html lang="tr">
<head>
    <meta charset="utf-8" />
   
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>01| Admin İçerik Paneli </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="@Url.Content("~/Content/Admin/css/bootstrap.min.css")" rel="stylesheet" />
    <!--  Light Bootstrap Table core CSS    -->
    <link href="@Url.Content("~/Content/Admin/css/light-bootstrap-dashboard.css?v=1.4.0")" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="@Url.Content("~/Content/Admin/css/demo.css")" rel="stylesheet" />
  
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="@Url.Content("~/Content/Admin/css/pe-icon-7-stroke.css")" rel="stylesheet" />
  
    <script src="@Url.Content("~/ckeditor/ckeditor.js")"></script>  
</head>
<body>
    
    <div class="wrapper">
        <div class="sidebar" data-image="@Url.Content("~/Content/Admin/img/sidebar-4.jpg")" data-color="orange">
           
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a class="simple-text" href="/AdminPanel/Index" title="Anasayfa">
                        01 | Özel Ders Adana
                    </a>
                </div>

                <ul class="nav">
                    <li>
                        <a href="/AdminPanel/Yazılar">
                            <i class="pe-7s-note2"></i>
                            <p>Yazılar</p>
                        </a>
                    </li>

                    <li>
                         <a href="/AdminPanel/Resimler">
                            <i class="pe-7s-album"></i>
                                <p>Resimler</p>
                         </a>
                   </li>
                   
                    <li>
                        <a href="/AdminPanel/Tarih">
                            <i class="pe-7s-timer"></i>
                            <p>Zamanlayıcılar</p>
                        </a>
                    </li>
                    <li>
                        <a href="/AdminPanel/İletisim">
                            <i class="pe-7s-way"></i>
                            <p>İletişim</p>
                        </a>
                    </li>


                    <li class="active-pro">
                        <a href="/Login">
                            <i class="pe-7s-next-2"></i>
                            <p style="text-align:center; font-size:17px">ÇIKIŞ YAP</p>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="sidebar-background" style="background-image: @Url.Content("~/Content/Admin/img/sidebar-4.jpg") "></div>
        </div>

        <div class="main-panel" >
            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-target="#navigation-example-2" data-toggle="collapse">
                            <span class="sr-only"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                       
                    </div>

                    <div class="collapse navbar-collapse"></div>

                </div>
            </nav>

            <div class="content"> 
                <div class="container-fluid">
                     @RenderBody()
                </div>
            </div>
        </div>
    </div>


    <script src="@Url.Content("~/Content/Admin/js/jquery.3.2.1.min.js")"></script>
    <script src="@Url.Content("~/Content/Admin/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Content/Admin/js/light-bootstrap-dashboard.js")"></script>
</body>
</html>